class Split1 {
    public Split1(InputStreamReader rdr) { ...
        public void readNextLine() throws IOException { ...
            public int numFields() { ...
                public String getField(int fieldNo) { ...
                }
                class Split2 {
                    public Split2(String line) { ...
                        public int numFields() { ...
                            public String getField(int fieldNo) { ...
                            }